services:
  java-app:
    container_name: java-app
    image: 192.168.122.23:8083/java-app:1.0
    ports: 
      - 8080:8080
    environment:
      - DB_USER
      - DB_PWD
      - DB_SERVER=mysql
      - DB_NAME=projects
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql
    image: mysql:9.5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=projects
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
     - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","mysql"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.3-apache
    ports:
     - 8081:80
    environment:
      PMA_HOST: mysql
volumes:
  mysql-data:
    driver: local
