services:
  mysql:
    image: mysql:9.5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projects
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
     - mysql-data:/data/db
  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    ports:
     - 8081:80
    environment:
      PMA_HOST: mysql
volumes:
  mysql-data:
    driver: local
